version: '3'
services:
  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: somehomedb
    volumes:
      - ./database:/var/lib/postgresql/data
  somehome:
    image: mevid93/somehome:v1
    environment:
      DB_HOSTNAME: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres
